#!/bin/zsh
#参考にさせていただいたもの:https://github.com/b4b4r07/dotfiles/blob/master/bin/battery

percent=`pmset -g ps | grep -o '[0-9]\+%' | tr -d '%'`
pmset -g ps | grep -E "Battery Power|charged" >/dev/null 2>&1
if [ $? -eq 0  ]; then

  time=`pmset -g ps | grep -o '[0-9]\+:[0-9]\+'`
  
  if [ -z "$time" ]; then
    if [ $percent -le 20 ] ; then
      echo -e "#[bg=colour196]#[fg=colour015] ${percent}% #[default]"
    else
      echo -e "#[bg=colour027]#[fg=colour015] ${percent}% #[default]"
    fi
  else
    if [ $percent -le 20 ] ; then
      echo -e "#[bg=colour196]#[fg=colour015] ${percent}% (${time}) #[default]"
    else
      echo -e "#[bg=colour027]#[fg=colour015] ${percent}% (${time}) #[default]"
    fi
  fi
else
  echo -e "#[bg=colour082]#[fg=black] ${percent}% #[default]"
fi
